import type { Lang, Module, Section } from "./types";

export const TAKSHA_MODULES: Module[] = [
  {
    id: "M01-workshop-safety",
    title_en: "Workshop Safety and Work Discipline",
    title_bn: "ওয়ার্কশপ নিরাপত্তা ও কাজের শৃঙ্খলা",
    title_hi: "वर्कशॉप सुरक्षा और काम का अनुशासन",
    icon: "🛡️",
    sort_order: 1,
    theory_hours: 3,
    practical_hours: 5,
    group_key: "foundation",
    group_label_en: "Foundation",
    group_label_bn: "ভিত্তি",
    group_label_hi: "आधार",
  },
  {
    id: "M02-tools",
    title_en: "Hand Tools, Power Tools, and Maintenance",
    title_bn: "হাতের টুল, পাওয়ার টুল ও রক্ষণাবেক্ষণ",
    title_hi: "हैंड टूल, पावर टूल और रखरखाव",
    icon: "🧰",
    sort_order: 2,
    theory_hours: 4,
    practical_hours: 8,
    group_key: "foundation",
    group_label_en: "Foundation",
    group_label_bn: "ভিত্তি",
    group_label_hi: "आधार",
  },
  {
    id: "M03-measure-mark",
    title_en: "Measurement, Marking, and Layout",
    title_bn: "মাপ নেওয়া, মার্কিং ও লেআউট",
    title_hi: "माप, मार्किंग और लेआउट",
    icon: "📏",
    sort_order: 3,
    theory_hours: 4,
    practical_hours: 8,
    group_key: "foundation",
    group_label_en: "Foundation",
    group_label_bn: "ভিত্তি",
    group_label_hi: "आधार",
  },
  {
    id: "M04-wood-materials",
    title_en: "Wood Types, Boards, Hardware, and Adhesives",
    title_bn: "কাঠের ধরন, বোর্ড, হার্ডওয়্যার ও আঠা",
    title_hi: "लकड़ी के प्रकार, बोर्ड, हार्डवेयर और गोंद",
    icon: "🪵",
    sort_order: 4,
    theory_hours: 5,
    practical_hours: 6,
    group_key: "materials",
    group_label_en: "Materials",
    group_label_bn: "উপকরণ",
    group_label_hi: "सामग्री",
  },
  {
    id: "M05-cutting-joining",
    title_en: "Cutting, Shaping, and Joinery",
    title_bn: "কাটা, আকার দেওয়া ও জয়নারি",
    title_hi: "कटिंग, आकार देना और जोड़ाई",
    icon: "🪚",
    sort_order: 5,
    theory_hours: 5,
    practical_hours: 12,
    group_key: "core_skills",
    group_label_en: "Core Skills",
    group_label_bn: "মূল দক্ষতা",
    group_label_hi: "मुख्य कौशल",
  },
  {
    id: "M06-furniture-basics",
    title_en: "Furniture Frames, Cabinets, and Drawers",
    title_bn: "ফার্নিচার ফ্রেম, ক্যাবিনেট ও ড্রয়ার",
    title_hi: "फर्नीचर फ्रेम, कैबिनेट और दराज",
    icon: "🪑",
    sort_order: 6,
    theory_hours: 5,
    practical_hours: 14,
    group_key: "core_skills",
    group_label_en: "Core Skills",
    group_label_bn: "মূল দক্ষতা",
    group_label_hi: "मुख्य कौशल",
  },
  {
    id: "M07-finishing",
    title_en: "Sanding, Finishing, Polishing, and Protection",
    title_bn: "স্যান্ডিং, ফিনিশিং, পলিশিং ও সুরক্ষা",
    title_hi: "सैंडिंग, फिनिशिंग, पॉलिशिंग और सुरक्षा",
    icon: "🎨",
    sort_order: 7,
    theory_hours: 4,
    practical_hours: 10,
    group_key: "finishing",
    group_label_en: "Finishing",
    group_label_bn: "ফিনিশিং",
    group_label_hi: "फिनिशिंग",
  },
  {
    id: "M08-site-installation",
    title_en: "Site Work, Installation, and Client Handover",
    title_bn: "সাইটের কাজ, ইনস্টলেশন ও ক্লায়েন্ট হ্যান্ডওভার",
    title_hi: "साइट वर्क, इंस्टॉलेशन और क्लाइंट हैंडओवर",
    icon: "🏗️",
    sort_order: 8,
    theory_hours: 4,
    practical_hours: 10,
    group_key: "field_work",
    group_label_en: "Field Work",
    group_label_bn: "সাইটের কাজ",
    group_label_hi: "साइट का काम",
  },
  {
    id: "M09-repair",
    title_en: "Repair, Restoration, and Problem Solving",
    title_bn: "মেরামত, পুনরুদ্ধার ও সমস্যা সমাধান",
    title_hi: "मरम्मत, बहाली और समस्या समाधान",
    icon: "🔧",
    sort_order: 9,
    theory_hours: 4,
    practical_hours: 10,
    group_key: "field_work",
    group_label_en: "Field Work",
    group_label_bn: "সাইটের কাজ",
    group_label_hi: "साइट का काम",
  },
  {
    id: "M10-advanced-craft",
    title_en: "Advanced Craftsmanship and Professional Practice",
    title_bn: "উন্নত কারিগরি দক্ষতা ও পেশাদার কাজ",
    title_hi: "उन्नत कारीगरी और पेशेवर अभ्यास",
    icon: "🏆",
    sort_order: 10,
    theory_hours: 5,
    practical_hours: 16,
    group_key: "professional",
    group_label_en: "Professional",
    group_label_bn: "পেশাদার",
    group_label_hi: "पेशेवर",
  },
];

const moduleBodies: Record<string, Record<Lang, string>> = {
  "M01-workshop-safety": {
    en: "Learn safe workshop habits before touching any tool: PPE, dust control, machine guards, cable discipline, sharp-tool handling, fire safety, first aid, and clean work zones.\n\nObjectives:\n- Identify common workshop hazards.\n- Use eye, ear, hand, and respiratory protection correctly.\n- Set up a clean bench and safe material flow.\n\nPractical exercise: inspect a workbench, list five hazards, correct them, and explain the safety reason for each correction.\n\nQuiz topics: PPE, tool guards, electrical safety, dust safety, emergency response.",
    bn: "কোনো টুল ধরার আগে নিরাপদ ওয়ার্কশপ অভ্যাস শিখো: পিপিই, ধুলো নিয়ন্ত্রণ, মেশিন গার্ড, কেবল গুছিয়ে রাখা, ধারালো টুল ধরা, আগুনের নিরাপত্তা, প্রাথমিক চিকিৎসা এবং পরিষ্কার কাজের জায়গা।\n\nলক্ষ্য:\n- ওয়ার্কশপের সাধারণ বিপদ চিনতে পারা।\n- চোখ, কান, হাত ও শ্বাসের সুরক্ষা ঠিকভাবে ব্যবহার করা।\n- পরিষ্কার বেঞ্চ ও নিরাপদ মাল চলাচলের ব্যবস্থা করা।\n\nপ্র্যাকটিক্যাল কাজ: একটি ওয়ার্কবেঞ্চ পরীক্ষা করো, পাঁচটি ঝুঁকি লিখো, সেগুলি ঠিক করো এবং প্রতিটি সংশোধনের নিরাপত্তা কারণ বোঝাও।\n\nকুইজ বিষয়: পিপিই, টুল গার্ড, বিদ্যুৎ নিরাপত্তা, ধুলো নিরাপত্তা, জরুরি ব্যবস্থা।",
    hi: "किसी भी टूल को छूने से पहले सुरक्षित वर्कशॉप आदतें सीखो: पीपीई, धूल नियंत्रण, मशीन गार्ड, केबल अनुशासन, धारदार टूल संभालना, आग से सुरक्षा, प्राथमिक उपचार और साफ काम की जगह।\n\nलक्ष्य:\n- वर्कशॉप के सामान्य खतरे पहचानना।\n- आंख, कान, हाथ और सांस की सुरक्षा सही तरह इस्तेमाल करना।\n- साफ बेंच और सुरक्षित सामग्री प्रवाह बनाना।\n\nप्रैक्टिकल काम: एक वर्कबेंच जांचो, पांच खतरे लिखो, उन्हें ठीक करो और हर सुधार का सुरक्षा कारण समझाओ।\n\nक्विज विषय: पीपीई, टूल गार्ड, बिजली सुरक्षा, धूल सुरक्षा, आपातकालीन प्रतिक्रिया।",
  },
  "M02-tools": {
    en: "Understand what each carpentry tool is for and how to keep it accurate. Covers measuring tools, saws, chisels, planes, drills, routers, clamps, sanders, and basic maintenance.\n\nPractical exercise: sharpen a chisel, square a blade, test a drill bit, and create a daily tool checklist.\n\nQuiz topics: tool selection, maintenance, safe operation, clamping, blade and bit care.",
    bn: "প্রতিটি কার্পেন্ট্রি টুল কী কাজে লাগে এবং কীভাবে সেটি ঠিক ও নির্ভুল রাখা যায় তা বোঝো। মাপের টুল, করাত, ছেনি, প্লেন, ড্রিল, রাউটার, ক্ল্যাম্প, স্যান্ডার এবং বেসিক রক্ষণাবেক্ষণ শেখানো হবে।\n\nপ্র্যাকটিক্যাল কাজ: ছেনি ধার দাও, ব্লেড স্কোয়ার করো, ড্রিল বিট পরীক্ষা করো এবং দৈনিক টুল চেকলিস্ট বানাও।\n\nকুইজ বিষয়: টুল নির্বাচন, রক্ষণাবেক্ষণ, নিরাপদ ব্যবহার, ক্ল্যাম্পিং, ব্লেড ও বিটের যত্ন।",
    hi: "हर कारपेंट्री टूल किस काम आता है और उसे सही व सटीक कैसे रखना है, यह समझो। इसमें मापने के टूल, आरी, छेनी, प्लेन, ड्रिल, राउटर, क्लैंप, सैंडर और बेसिक रखरखाव शामिल हैं।\n\nप्रैक्टिकल काम: छेनी तेज करो, ब्लेड को स्क्वायर करो, ड्रिल बिट जांचो और दैनिक टूल चेकलिस्ट बनाओ।\n\nक्विज विषय: टूल चयन, रखरखाव, सुरक्षित संचालन, क्लैंपिंग, ब्लेड और बिट की देखभाल।",
  },
  "M03-measure-mark": {
    en: "Good carpentry begins with accurate layout. Practice reading drawings, using tape and square correctly, marking reference faces, allowing tolerances, and checking diagonals.\n\nPractical exercise: mark and cut four pieces for a square frame within a 2 mm tolerance.\n\nQuiz topics: tolerances, squareness, reference edges, marking tools, drawing interpretation.",
    bn: "ভালো কার্পেন্ট্রি শুরু হয় সঠিক লেআউট দিয়ে। ড্রইং পড়া, টেপ ও স্কোয়ার ঠিকভাবে ব্যবহার, রেফারেন্স মুখ মার্ক করা, টলারেন্স রাখা এবং ডায়াগোনাল চেক করা অনুশীলন করো।\n\nপ্র্যাকটিক্যাল কাজ: ২ মিমি টলারেন্সের মধ্যে স্কোয়ার ফ্রেমের জন্য চারটি পিস মার্ক করে কাটো।\n\nকুইজ বিষয়: টলারেন্স, স্কোয়ারনেস, রেফারেন্স এজ, মার্কিং টুল, ড্রইং বোঝা।",
    hi: "अच्छी कारपेंट्री सही लेआउट से शुरू होती है। ड्रॉइंग पढ़ना, टेप और स्क्वायर सही तरह इस्तेमाल करना, रेफरेंस फेस मार्क करना, टॉलरेंस रखना और डायगोनल जांचना अभ्यास करो।\n\nप्रैक्टिकल काम: २ मिमी टॉलरेंस के अंदर स्क्वायर फ्रेम के लिए चार पीस मार्क करके काटो।\n\nक्विज विषय: टॉलरेंस, स्क्वायरनेस, रेफरेंस एज, मार्किंग टूल, ड्रॉइंग समझना।",
  },
  "M04-wood-materials": {
    en: "Study solid wood, plywood, MDF, particle board, laminates, veneers, screws, hinges, channels, adhesives, and how moisture affects material movement.\n\nPractical exercise: compare three board samples, choose hardware for a cabinet, and explain why the choice fits the job.\n\nQuiz topics: wood movement, board selection, adhesives, fasteners, hardware.",
    bn: "সলিড উড, প্লাইউড, এমডিএফ, পার্টিকল বোর্ড, ল্যামিনেট, ভিনিয়ার, স্ক্রু, হিঞ্জ, চ্যানেল, আঠা এবং আর্দ্রতা কীভাবে উপকরণের নড়াচড়ায় প্রভাব ফেলে তা শিখো।\n\nপ্র্যাকটিক্যাল কাজ: তিনটি বোর্ড স্যাম্পল তুলনা করো, ক্যাবিনেটের জন্য হার্ডওয়্যার বেছে নাও এবং কেন সেটি কাজের জন্য ঠিক তা বোঝাও।\n\nকুইজ বিষয়: কাঠের মুভমেন্ট, বোর্ড নির্বাচন, আঠা, ফাস্টেনার, হার্ডওয়্যার।",
    hi: "सॉलिड वुड, प्लाइवुड, एमडीएफ, पार्टिकल बोर्ड, लैमिनेट, विनियर, स्क्रू, हिंग, चैनल, गोंद और नमी से सामग्री की मूवमेंट कैसे बदलती है, यह सीखो।\n\nप्रैक्टिकल काम: तीन बोर्ड सैंपल की तुलना करो, कैबिनेट के लिए हार्डवेयर चुनो और समझाओ कि वह काम के लिए क्यों सही है।\n\nक्विज विषय: लकड़ी की मूवमेंट, बोर्ड चयन, गोंद, फास्टनर, हार्डवेयर।",
  },
  "M05-cutting-joining": {
    en: "Build core cutting and joining skill: rip cuts, cross cuts, mitres, curves, dados, rabbets, dowels, pocket screws, mortise and tenon, and basic jigs.\n\nPractical exercise: make a small joined frame using two joinery methods and test it for square and strength.\n\nQuiz topics: saw setup, grain direction, joinery choice, glue-up, clamping pressure.",
    bn: "কাটিং ও জয়নারির মূল দক্ষতা তৈরি করো: রিপ কাট, ক্রস কাট, মাইটার, কার্ভ, ড্যাডো, র্যাবেট, ডাওয়েল, পকেট স্ক্রু, মর্টিস-টেনন এবং বেসিক জিগ।\n\nপ্র্যাকটিক্যাল কাজ: দুই ধরনের জয়নারি ব্যবহার করে ছোট ফ্রেম বানাও এবং সেটি স্কোয়ার ও শক্ত কিনা পরীক্ষা করো।\n\nকুইজ বিষয়: করাত সেটআপ, গ্রেন দিক, জয়নারি নির্বাচন, গ্লু-আপ, ক্ল্যাম্পিং চাপ।",
    hi: "कटिंग और जोड़ाई की मुख्य कौशल बनाओ: रिप कट, क्रॉस कट, माइटर, कर्व, डैडो, रैबेट, डॉवेल, पॉकेट स्क्रू, मॉर्टिस-टेनन और बेसिक जिग।\n\nप्रैक्टिकल काम: दो जोड़ाई तरीकों से छोटा फ्रेम बनाओ और उसे स्क्वायर व मजबूत होने के लिए जांचो।\n\nक्विज विषय: आरी सेटअप, ग्रेन दिशा, जोड़ाई चयन, ग्लू-अप, क्लैंपिंग दबाव।",
  },
  "M06-furniture-basics": {
    en: "Move from parts to furniture. Learn frame construction, carcass building, shelves, shutters, drawers, edge banding, alignment, and simple ergonomic dimensions.\n\nPractical exercise: build a small wall cabinet or stool with a measured drawing and cutting list.\n\nQuiz topics: carcass layout, drawer clearance, hinges, load paths, assembly order.",
    bn: "পার্ট থেকে ফার্নিচারে যাও। ফ্রেম বানানো, কারকাস বিল্ডিং, শেলফ, শাটার, ড্রয়ার, এজ ব্যান্ডিং, অ্যালাইনমেন্ট এবং সহজ আরগোনমিক মাপ শিখো।\n\nপ্র্যাকটিক্যাল কাজ: মাপসহ ড্রইং ও কাটিং লিস্ট দিয়ে একটি ছোট ওয়াল ক্যাবিনেট বা স্টুল বানাও।\n\nকুইজ বিষয়: কারকাস লেআউট, ড্রয়ার ক্লিয়ারেন্স, হিঞ্জ, লোড পাথ, অ্যাসেম্বলি অর্ডার।",
    hi: "पार्ट्स से फर्नीचर तक बढ़ो। फ्रेम बनाना, कारकस बिल्डिंग, शेल्फ, शटर, दराज, एज बैंडिंग, अलाइनमेंट और सरल एर्गोनॉमिक माप सीखो।\n\nप्रैक्टिकल काम: माप वाली ड्रॉइंग और कटिंग लिस्ट से छोटा वॉल कैबिनेट या स्टूल बनाओ।\n\nक्विज विषय: कारकस लेआउट, दराज क्लियरेंस, हिंग, लोड पाथ, असेंबली ऑर्डर।",
  },
  "M07-finishing": {
    en: "Learn surface preparation and finish selection: sanding sequence, filling, staining, sealing, polishing, varnish, PU, oil, wax, and protection during transport.\n\nPractical exercise: prepare three sample boards with different finishes and compare appearance, touch, and durability.\n\nQuiz topics: grit sequence, stain control, finish compatibility, defects, curing.",
    bn: "সারফেস প্রস্তুতি ও ফিনিশ নির্বাচন শিখো: স্যান্ডিং সিকোয়েন্স, ফিলিং, স্টেইনিং, সিলিং, পলিশিং, ভার্নিশ, পিইউ, তেল, মোম এবং পরিবহনের সময় সুরক্ষা।\n\nপ্র্যাকটিক্যাল কাজ: তিনটি স্যাম্পল বোর্ডে আলাদা ফিনিশ করো এবং চেহারা, স্পর্শ ও টেকসইপনা তুলনা করো।\n\nকুইজ বিষয়: গ্রিট সিকোয়েন্স, স্টেইন কন্ট্রোল, ফিনিশ সামঞ্জস্য, ত্রুটি, কিউরিং।",
    hi: "सतह तैयारी और फिनिश चयन सीखो: सैंडिंग क्रम, फिलिंग, स्टेनिंग, सीलिंग, पॉलिशिंग, वार्निश, पीयू, तेल, वैक्स और परिवहन के समय सुरक्षा।\n\nप्रैक्टिकल काम: तीन सैंपल बोर्ड पर अलग फिनिश करो और रूप, स्पर्श व टिकाऊपन की तुलना करो।\n\nक्विज विषय: ग्रिट क्रम, स्टेन नियंत्रण, फिनिश संगतता, दोष, क्योरिंग।",
  },
  "M08-site-installation": {
    en: "Practice real site work: measurement verification, wall/floor checks, anchoring, leveling, scribing, client communication, snag lists, and handover.\n\nPractical exercise: install a shelf or cabinet mock-up on an uneven wall and create a handover checklist.\n\nQuiz topics: anchors, leveling, site measurement, snag correction, client handover.",
    bn: "বাস্তব সাইটের কাজ অনুশীলন করো: মাপ যাচাই, দেয়াল/মেঝে চেক, অ্যাঙ্করিং, লেভেলিং, স্ক্রাইবিং, ক্লায়েন্টের সঙ্গে কথা, স্ন্যাগ লিস্ট এবং হ্যান্ডওভার।\n\nপ্র্যাকটিক্যাল কাজ: অসমান দেয়ালে একটি শেলফ বা ক্যাবিনেট মক-আপ ইনস্টল করো এবং হ্যান্ডওভার চেকলিস্ট বানাও।\n\nকুইজ বিষয়: অ্যাঙ্কর, লেভেলিং, সাইট মাপ, স্ন্যাগ সংশোধন, ক্লায়েন্ট হ্যান্ডওভার।",
    hi: "वास्तविक साइट काम का अभ्यास करो: माप सत्यापन, दीवार/फर्श जांच, एंकरिंग, लेवलिंग, स्क्राइबिंग, क्लाइंट संवाद, स्नैग लिस्ट और हैंडओवर।\n\nप्रैक्टिकल काम: असमान दीवार पर शेल्फ या कैबिनेट मॉक-अप लगाओ और हैंडओवर चेकलिस्ट बनाओ।\n\nक्विज विषय: एंकर, लेवलिंग, साइट माप, स्नैग सुधार, क्लाइंट हैंडओवर।",
  },
  "M09-repair": {
    en: "Learn diagnosis and repair: loose joints, swollen shutters, scratches, broken hardware, water damage, laminate peeling, and restoration planning.\n\nPractical exercise: inspect a damaged furniture piece, diagnose the cause, and prepare a repair estimate with steps.\n\nQuiz topics: fault diagnosis, repair sequence, material matching, hardware replacement, prevention.",
    bn: "ডায়াগনসিস ও মেরামত শিখো: ঢিলা জয়েন্ট, ফুলে যাওয়া শাটার, স্ক্র্যাচ, ভাঙা হার্ডওয়্যার, পানির ক্ষতি, ল্যামিনেট উঠে যাওয়া এবং রিস্টোরেশন পরিকল্পনা।\n\nপ্র্যাকটিক্যাল কাজ: ক্ষতিগ্রস্ত ফার্নিচার পরীক্ষা করো, কারণ নির্ণয় করো এবং ধাপসহ মেরামতের অনুমান বানাও।\n\nকুইজ বিষয়: ফল্ট ডায়াগনসিস, মেরামত সিকোয়েন্স, উপকরণ মেলানো, হার্ডওয়্যার বদল, প্রতিরোধ।",
    hi: "डायग्नोसिस और मरम्मत सीखो: ढीले जोड़, फूले हुए शटर, खरोंच, टूटा हार्डवेयर, पानी की क्षति, लैमिनेट छूटना और बहाली योजना।\n\nप्रैक्टिकल काम: खराब फर्नीचर पीस जांचो, कारण पहचानो और चरणों के साथ मरम्मत अनुमान बनाओ।\n\nक्विज विषय: फॉल्ट डायग्नोसिस, मरम्मत क्रम, सामग्री मिलान, हार्डवेयर बदलना, रोकथाम।",
  },
  "M10-advanced-craft": {
    en: "Develop professional judgment: complex joinery, templates, curved work, built-ins, quality inspection, costing, time planning, workshop leadership, and client-ready craftsmanship.\n\nPractical exercise: plan and build a capstone piece with drawing, cutting list, finish schedule, quality checklist, and final presentation.\n\nQuiz topics: advanced joinery, costing, QA, production planning, professional standards.",
    bn: "পেশাদার বিচারশক্তি তৈরি করো: জটিল জয়নারি, টেমপ্লেট, কার্ভড কাজ, বিল্ট-ইন, কোয়ালিটি পরীক্ষা, খরচ হিসাব, সময় পরিকল্পনা, ওয়ার্কশপ নেতৃত্ব এবং ক্লায়েন্ট-রেডি কারিগরি।\n\nপ্র্যাকটিক্যাল কাজ: ড্রইং, কাটিং লিস্ট, ফিনিশ শিডিউল, কোয়ালিটি চেকলিস্ট ও ফাইনাল প্রেজেন্টেশনসহ একটি ক্যাপস্টোন পিস পরিকল্পনা করে বানাও।\n\nকুইজ বিষয়: উন্নত জয়নারি, কস্টিং, কোয়ালিটি অ্যাসিউরেন্স, প্রোডাকশন পরিকল্পনা, পেশাদার মান।",
    hi: "पेशेवर निर्णय क्षमता विकसित करो: जटिल जोड़ाई, टेम्पलेट, कर्व्ड काम, बिल्ट-इन, क्वालिटी जांच, लागत, समय योजना, वर्कशॉप नेतृत्व और क्लाइंट-रेडी कारीगरी।\n\nप्रैक्टिकल काम: ड्रॉइंग, कटिंग लिस्ट, फिनिश शेड्यूल, क्वालिटी चेकलिस्ट और अंतिम प्रस्तुति के साथ एक कैपस्टोन पीस प्लान करके बनाओ।\n\nक्विज विषय: उन्नत जोड़ाई, लागत, क्वालिटी एश्योरेंस, प्रोडक्शन प्लानिंग, पेशेवर मानक।",
  },
};

const sectionTitle: Record<Lang, string> = {
  en: "Training Brief, Exercises, and Quiz Topics",
  bn: "ট্রেনিং ব্রিফ, অনুশীলন ও কুইজ বিষয়",
  hi: "ट्रेनिंग ब्रीफ, अभ्यास और क्विज विषय",
};

export function getTakshaSections(
  moduleId: string,
  lang: Lang = "en",
): Array<Section & { content: { body: string } }> {
  const mod = TAKSHA_MODULES.find((m) => m.id === moduleId);
  if (!mod) return [];
  const body = moduleBodies[moduleId]?.[lang] || moduleBodies[moduleId]?.en || "";
  return [
    {
      id: `${moduleId}-overview`,
      module_id: moduleId,
      title_en: sectionTitle.en,
      title_bn: sectionTitle.bn,
      title_hi: sectionTitle.hi,
      sort_order: 1,
      estimated_hours: mod.theory_hours + mod.practical_hours,
      content: { body },
    },
  ];
}
